import React, { useState } from 'react';

// Simple Modal Component
const LegalModal: React.FC<{ 
    isOpen: boolean; 
    onClose: () => void; 
    title: string; 
    children: React.ReactNode; 
}> = ({ isOpen, onClose, title, children }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
            <div className="bg-white dark:bg-gray-800 rounded-2xl max-w-lg w-full p-6 shadow-2xl border border-gray-200 dark:border-gray-700 animate-in fade-in zoom-in duration-200">
                <div className="flex justify-between items-center mb-4 border-b dark:border-gray-700 pb-2">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white">{title}</h3>
                    <button onClick={onClose} className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300">
                        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
                <div className="max-h-[60vh] overflow-y-auto custom-scrollbar">
                    {children}
                </div>
                <div className="mt-6 flex justify-end">
                    <button 
                        onClick={onClose}
                        className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};

export const Footer: React.FC = () => {
    const [modalState, setModalState] = useState<{isOpen: boolean, page: string | null, content: React.ReactNode | null}>({
        isOpen: false,
        page: null,
        content: null
    });
    const [disclaimerAccepted, setDisclaimerAccepted] = useState(false);

    const openPage = (pageName: string) => {
        setDisclaimerAccepted(false); // Reset disclaimer
        setModalState({ isOpen: true, page: pageName, content: null });
    };

    const handleAcceptDisclaimer = () => {
        setDisclaimerAccepted(true);
    };

    const getPageContent = (pageName: string | null) => {
        if (!pageName) return null;

        // Content Map
        const contentMap: Record<string, React.ReactNode> = {
            'About': (
                <div className="prose dark:prose-invert text-sm">
                    <p>Doodax is a cutting-edge AI platform designed to help creators streamline their workflow. Built by Hsini Mohamed, this tool leverages Gemini and Ollama to generate professional scripts.</p>
                </div>
            ),
            'Contact': (
                <div className="prose dark:prose-invert text-sm">
                    <p className="font-bold text-lg">Contact Information</p>
                    <p>For inquiries, support, or partnerships, please reach out:</p>
                    <ul className="list-none pl-0">
                        <li className="mb-2"><strong>Website:</strong> <a href="https://doodax.com" target="_blank" rel="noopener noreferrer" className="text-indigo-600">doodax.com</a></li>
                        <li><strong>Email:</strong> <a href="mailto:hsini.web@gmail.com" className="text-indigo-600">hsini.web@gmail.com</a></li>
                    </ul>
                </div>
            ),
            'Privacy Policy': (
                <div className="prose dark:prose-invert text-sm">
                    <p>We respect your privacy. This application runs primarily client-side. If using Local Ollama, no data leaves your network. If using Gemini, data is sent to Google Cloud AI solely for processing.</p>
                </div>
            ),
            'Terms of Service': (
                <div className="prose dark:prose-invert text-sm">
                    <p>By using Doodax, you agree to use the generated content responsibly. We are not liable for the content generated by AI models.</p>
                </div>
            ),
            'DMCA': (
                <div className="prose dark:prose-invert text-sm">
                    <p>Doodax respects intellectual property rights. If you believe your copyright has been infringed, please contact us via the email provided in the Contact section.</p>
                </div>
            ),
            'Guide': (
                <div className="prose dark:prose-invert text-sm">
                    <p>1. Enter a Title.<br/>2. Add an outline.<br/>3. Select duration.<br/>4. Click Generate.</p>
                </div>
            )
        };
        return contentMap[pageName] || <p>Content loading...</p>;
    };

    const links = ['About', 'Contact', 'Guide', 'Privacy Policy', 'Terms of Service', 'DMCA'];

    return (
        <footer className="mt-12 py-8 glass-panel border-t border-gray-200 dark:border-gray-700">
            <div className="container mx-auto px-4 max-w-5xl">
                
                {/* Links Grid */}
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-8 text-center md:text-left">
                    {links.map(link => (
                        <button 
                            key={link}
                            onClick={() => openPage(link)}
                            className="text-sm text-gray-600 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
                        >
                            {link}
                        </button>
                    ))}
                </div>

                <div className="border-t border-gray-200 dark:border-gray-700 pt-8 flex flex-col items-center">
                    <p className="text-gray-500 dark:text-gray-400 text-sm mb-2">
                        &copy; {new Date().getFullYear()} AI YouTube Scriptwriter. All rights reserved.
                    </p>
                    <p className="flex items-center gap-2 text-sm text-gray-900 dark:text-white font-medium">
                        Powered by 
                        <a 
                            href="https://github.com/hsinidev" 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-400 dark:to-purple-400 font-bold hover:scale-105 transition-transform"
                        >
                            HSINI MOHAMED
                        </a>
                    </p>
                </div>
            </div>

            {/* Modal Logic */}
            <LegalModal 
                isOpen={modalState.isOpen} 
                onClose={() => setModalState({ ...modalState, isOpen: false })}
                title={modalState.page || 'Info'}
            >
                {!disclaimerAccepted ? (
                    <div className="space-y-4 text-center py-4">
                        <div className="mx-auto w-16 h-16 bg-yellow-100 rounded-full flex items-center justify-center mb-4">
                            <svg className="w-8 h-8 text-yellow-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                            </svg>
                        </div>
                        <h4 className="text-lg font-bold text-gray-900 dark:text-white">Content Warning & Disclaimer</h4>
                        <p className="text-gray-600 dark:text-gray-300">
                            You are about to view legal or contact information. In compliance with Google policies and general transparency standards, please acknowledge that this tool is for assistance purposes.
                        </p>
                        <button 
                            onClick={handleAcceptDisclaimer}
                            className="mt-4 w-full px-4 py-3 bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-bold rounded-xl hover:opacity-90 transition-opacity"
                        >
                            Continue to {modalState.page}
                        </button>
                    </div>
                ) : (
                    getPageContent(modalState.page)
                )}
            </LegalModal>
        </footer>
    );
};